// Dummy data — replace with API calls when backend is connected

export const listings = [
  { id: '1', title: 'Farm/Plot for Sale — Glen Forest', titleSn: 'Purazi/Nzvimbo — Glen Forest', titleNd: 'Ifamu/Isikhala — Glen Forest', location: 'Glen Forest, Harare North', area: 'Harare', type: 'agricultural', listingType: 'sale', priceDisplay: 'USD 250,000', size: '1.62Ha', description: 'Small farming stand with title deeds. Ideal for poultry projects, small garden plots. 1.62 hectares in Glen Forest, Harare North.', descriptionSn: 'Nzvimbo duku yekurima ine mazita. Yakakodzera huku, minda miduku. 1.62 hektari muGlen Forest.', descriptionNd: 'Isiza esincane samasimu silomazwi wokusebenza. Sifanele amajuba, amasimu amancane. 1.62 hektare eGlen Forest.', featured: true, branch: 'harare' },
  { id: '2', title: 'Commercial Space to Rent — Victoria Falls', titleSn: 'Nzvimbo yebiznisi — Victoria Falls', titleNd: 'Indawo Yohwebo — Victoria Falls', location: 'Victoria Falls', area: 'Victoria Falls', type: 'commercial', listingType: 'rent', priceDisplay: 'USD 1,500/pm', size: '250m²', description: 'Prime commercial space in the heart of Victoria Falls. 250m² open-plan floor. Strategic location on the main road.', descriptionSn: 'Nzvimbo yebiznisi yepamutemo muVictoria Falls. 250m² yepamuti. Nzvimbo yakakodzera pamugwagwa mukuru.', descriptionNd: 'Indawo yohwebo enhle phakathi kweVictoria Falls. 250m² yendawo evulekile.', featured: true, branch: 'harare' },
  { id: '3', title: 'Large Farm for Sale — Glen Forest', titleSn: 'Purazi Huru — Glen Forest', titleNd: 'Ifamu Elikhulu — Glen Forest', location: 'Glen Forest, Harare North', area: 'Harare', type: 'agricultural', listingType: 'sale', priceDisplay: 'USD 4,000,000', size: '47.57Ha', description: 'Expansive 47.57 hectare farm in Glen Forest. Title deeds. Exceptional agricultural opportunity.', descriptionSn: 'Purazi huru ya 47.57 hektari muGlen Forest. Ine mazita. Mukana mukuru wezvirimo.', descriptionNd: 'Ifamu elikhulu le 47.57 hektare eGlen Forest. Lilomazwi. Ithuba elikhulu lamasimu.', featured: true, branch: 'harare' },
  { id: '4', title: 'Warehouse/Industrial for Sale — Zvishavane', titleSn: 'Imba yeStoreji — Zvishavane', titleNd: 'Indlu Yokugcina — Zvishavane', location: 'Zvishavane', area: 'Zvishavane', type: 'industrial', listingType: 'sale', priceDisplay: 'USD 1,400,000', size: '6,055m²', description: 'Industrial property on Kandodo Street, Zvishavane. 6,055m². Flexible purchase terms.', descriptionSn: 'Nzvimbo yeindasitiri paKandodo Street. 6,055m². Nzira dzekunotenga dzakasiyana.', descriptionNd: 'Indawo yezezimboni eKandodo Street. 6,055m². Izindlela zokungenisa ezikhona.', featured: false, branch: 'marondera' },
  { id: '5', title: 'Industrial Stand — Arcadia/Tynwald', titleSn: 'Stand yeIndasitiri — Arcadia/Tynwald', titleNd: 'Isiza Sezezimboni — Arcadia/Tynwald', location: 'Arcadia, Tynwald, Harare', area: 'Harare', type: 'industrial', listingType: 'sale', priceDisplay: 'USD 2,000,000', size: '8,000m²', description: 'Industrial stand for sale in Arcadia/Tynwald. 8,000m². Prime industrial location in Harare.', descriptionSn: 'Stand yeindasitiri muArcadia/Tynwald. 8,000m².', descriptionNd: 'Isiza sezezimboni eArcadia/Tynwald. 8,000m².', featured: false, branch: 'harare' },
  { id: '6', title: 'Commercial Stand — Bindura', titleSn: 'Stand yebiznisi — Bindura', titleNd: 'Isiza Sohwebo — Bindura', location: 'Bindura', area: 'Bindura', type: 'commercial', listingType: 'sale', priceDisplay: 'USD 250,000', size: '4,813m²', description: 'Great location commercial stand in Bindura. Ideal for hardware shop or store. 4,813m².', descriptionSn: 'Nzvimbo yebiznisi yakakodzera mubindura. Yakakodzera kuvaka chitoro.', descriptionNd: 'Isiza sohwebo esinhle eBindura. Sifanele ukwakha isitolo.', featured: true, branch: 'marondera' },
  { id: '7', title: 'Industrial Land — Tynwald', titleSn: 'Nzvimbo yeindasitiri — Tynwald', titleNd: 'Umhlabathi Wezezimboni — Tynwald', location: 'Tynwald, Harare West', area: 'Harare', type: 'industrial', listingType: 'sale', priceDisplay: 'USD 1,050,000', size: '8,503m²', description: 'Big piece of industrial land on the main road in Tynwald. Perfect for warehousing and truck parking.', descriptionSn: 'Nzvimbo huru yeindasitiri pamugwagwa mukuru muTynwald.', descriptionNd: 'Umhlabathi omkhulu wezezimboni emgwaqweni omkhulu eTynwald.', featured: false, branch: 'harare' },
  { id: '8', title: 'Premium Commercial Rental — Victoria Falls', titleSn: 'Nzvimbo Yebiznisi Huru — Victoria Falls', titleNd: 'Indawo Enkulu Yohwebo — Victoria Falls', location: 'Victoria Falls', area: 'Victoria Falls', type: 'commercial', listingType: 'rent', priceDisplay: 'USD 2,500/pm', size: '350m²', description: 'Premium commercial space on Soper Road, Victoria Falls. High-traffic area. Excellent business opportunity.', descriptionSn: 'Nzvimbo yebiznisi yepamusoro paSoper Road, Victoria Falls.', descriptionNd: 'Indawo enkulu yohwebo eSoper Road, Victoria Falls.', featured: false, branch: 'harare' },
  { id: '9', title: 'Warehouse/Industrial — Chiredzi', titleSn: 'Imba yeStoreji — Chiredzi', titleNd: 'Indlu Yokugcina — Chiredzi', location: 'Chiredzi', area: 'Chiredzi', type: 'industrial', listingType: 'sale', priceDisplay: 'USD 800,000', size: '6,000m²', description: 'Prime industrial property for sale in Chiredzi. Entering town. Sellers willing to sell and lease back.', descriptionSn: 'Nzvimbo yepamutemo yeindasitiri muChiredzi.', descriptionNd: 'Indawo esemthethweni yezezimboni eChiredzi.', featured: false, branch: 'marondera' },
]

export const agents = [
  { id: 'agent-1', name: 'Senior Agent — Harare', role: 'Principal Agent', roleSn: 'Mumiririri Mukuru', roleNd: 'Umsebenzi Omkhulu', branch: 'harare', phone: '+263 4 000 0000', email: 'harare@mercers.co.zw', bio: 'Senior property specialist with extensive knowledge of the Harare commercial and industrial market. Specializing in large agricultural and industrial transactions.', bioSn: 'Nyanzvi yepfuma ine ruzivo rwakawanda wemahara webiznisi uye indasitiri.', bioNd: 'Uchwepheshe wezindawo olomalwazi mayelana nezimakethe zeHarare zohwebo lezezimboni.', specialties: ['Commercial', 'Industrial', 'Agricultural'] },
  { id: 'agent-2', name: 'Commercial Specialist — Harare', role: 'Commercial Agent', roleSn: 'Mumiririri webiznisi', roleNd: 'Umsebenzi Wohwebo', branch: 'harare', phone: '+263 4 000 0001', email: 'commercial@mercers.co.zw', bio: 'Dedicated commercial property agent with expertise in the Victoria Falls tourism and hospitality sector. Strong network across Zimbabwe\'s commercial property market.', bioSn: 'Mumiririri ane ruzivo rwezviwanikwa zvekuVictoria Falls uye zvekushanyirwa.', bioNd: 'Umsebenzi olomalwazi ezindaweni zohwebo lezokuvakasha eVictoria Falls.', specialties: ['Commercial', 'Tourism', 'Hospitality'] },
  { id: 'agent-3', name: 'Industrial Specialist — Marondera', role: 'Industrial Agent', roleSn: 'Mumiririri weIndasitiri', roleNd: 'Umsebenzi Wezezimboni', branch: 'marondera', phone: '+263 79 000 0000', email: 'marondera@mercers.co.zw', bio: 'Industrial property expert covering Marondera, Zvishavane and Chiredzi. Deep knowledge of southern Zimbabwe\'s industrial landscape.', bioSn: 'Nyanzvi yenzvimbo dzeindasitiri dzeMurondera, Zvishavane neChiredzi.', bioNd: 'Uchwepheshe wezindawo zezezimboni eMarondera, Zvishavane leChiredzi.', specialties: ['Industrial', 'Warehousing', 'Commercial'] },
  { id: 'agent-4', name: 'Dawn Brown', role: 'Branch Manager — Marondera', roleSn: 'Maneja weHofisi — Murondera', roleNd: 'Umphathi Wehovisi — Marondera', branch: 'marondera', phone: '+263 79 000 0001', email: 'dawn@mercers.co.zw', bio: 'Branch Manager of Mercers\' new Marondera office. Dawn brings local knowledge and a passion for connecting clients with their ideal properties across Mashonaland East.', bioSn: 'Maneja weHofisi itsva yeMercers yeMurondera. Dawn ane ruzivo rwenyika.', bioNd: 'Umphathi Wehovisi Elisha LeMercers eMarondera. UDawn unemalwazi amaningi endawo.', specialties: ['Residential', 'Commercial', 'Agricultural'] },
]

export const translations = {
  en: {
    nav: { home: 'Home', listings: 'Listings', agents: 'Our Agents', contact: 'Contact' },
    hero: { tagline: 'Find Your Perfect Property in Zimbabwe', subtitle: 'Trusted estate agents across Harare and Marondera — commercial, industrial, agricultural and residential.', searchPlaceholder: 'Search by location, type or price...', searchBtn: 'Search', talkToAgent: 'Talk to Our AI Agent' },
    listings: { title: 'Featured Listings', allListings: 'View All Listings', forSale: 'For Sale', forRent: 'For Rent', viewMore: 'View More', filters: { all: 'All', residential: 'Residential', commercial: 'Commercial', industrial: 'Industrial', agricultural: 'Agricultural' } },
    agents: { title: 'Meet Our Agents', subtitle: 'Experienced professionals across Harare and Marondera', harare: 'Harare Office', marondera: 'Marondera Office', contact: 'Contact Agent' },
    about: { title: 'About Mercers', body: 'Mercers Kensington is a registered member of the Estate Agents Council of Zimbabwe. With decades of experience, we specialize in commercial, industrial, agricultural and residential properties across Zimbabwe.', council: 'Estate Agents Council Member', branches: 'Two Branches', branchesDetail: 'Harare & Marondera' },
    contact: { title: 'Get In Touch', name: 'Full Name', email: 'Email Address', phone: 'Phone Number', message: 'Your Message', send: 'Send Message', address: '19 Kay Gardens, Kensington, Harare, Zimbabwe' },
    chat: { title: 'Mercers AI Agent', subtitle: 'Ask me anything about our properties', placeholder: 'Ask about listings, prices, areas...', send: 'Send', welcome: "Hello! I'm the Mercers AI agent. I can help you find the perfect property in Zimbabwe — commercial, industrial, agricultural or residential. What are you looking for?" },
    footer: { tagline: 'Your trusted property partner in Zimbabwe', quickLinks: 'Quick Links', contactUs: 'Contact Us', follow: 'Follow Us', rights: '© 2026 Mercers Kensington. All rights reserved.', council: 'Registered Estate Agents Council Member' },
  },
  sn: {
    nav: { home: 'Musha', listings: 'Misha Inotenga', agents: 'Vagadzirisani Vedu', contact: 'Taura Nesu' },
    hero: { tagline: 'Tsvaga Imba Yako muZimbabwe', subtitle: 'Vagadzirisani vanovimbika muHarare neMurondera — misha yekutengeswa uye kuganhiwa.', searchPlaceholder: 'Tsvaga nenzvimbo, rudzi, kana mutengo...', searchBtn: 'Tsvaga', talkToAgent: 'Taura neMumiririri wedu' },
    listings: { title: 'Misha Yakanyanya', allListings: 'Ona Misha Yose', forSale: 'Inotenga', forRent: 'Inoganhiwa', viewMore: 'Ona Zvimwe', filters: { all: 'Zvose', residential: 'Yokugara', commercial: 'Yebiznisi', industrial: 'Yeindasitiri', agricultural: 'Yezvirimo' } },
    agents: { title: 'Vagadzirisani Vedu', subtitle: 'Nyanzvi dzeHarare neMurondera', harare: 'Hofisi yeHarare', marondera: 'Hofisi yeMurondera', contact: 'Taura neMumiririri' },
    about: { title: 'Nezvemercers', body: 'Mercers Kensington nhengo yeEstate Agents Council yeZimbabwe.', council: 'Nhengo yeEstate Agents Council', branches: 'Mahovisi Maviri', branchesDetail: 'Harare & Murondera' },
    contact: { title: 'Taura Nesu', name: 'Zita Rizere', email: 'Kero yeEmail', phone: 'Nhamba yeRunhare', message: 'Meseji Yako', send: 'Tumira Meseji', address: '19 Kay Gardens, Kensington, Harare, Zimbabwe' },
    chat: { title: 'Mumiririri weMercers', subtitle: 'Bvunza chero chinhu nezveimba dzedu', placeholder: 'Bvunza nezveimba, mitengo, nzvimbo...', send: 'Tumira', welcome: 'Mhoro! Ndini mumiririri weMercers. Ndinokubatsira kuwana imba yakanaka muZimbabwe. Unoda chii?' },
    footer: { tagline: 'Mumiririri wako wepfuma muZimbabwe', quickLinks: 'Zvinongedzo', contactUs: 'Taura Nesu', follow: 'Tiverenge', rights: '© 2026 Mercers Kensington. Kodzero dzose dzakachengeterwa.', council: 'Nhengo Yakanyoreswa yeEstate Agents Council' },
  },
  nd: {
    nav: { home: 'Ikhaya', listings: 'Izindawo', agents: 'Abasebenzi Bethu', contact: 'Xhumana Nathi' },
    hero: { tagline: 'Thola Indawo Yakho eZimbabwe', subtitle: 'Abasebenzi bakho abathembekileyo eHarare laseMarondera — izindawo zohwebo, amafemu kanye nezindlu.', searchPlaceholder: 'Cinga ngendawo, uhlobo, noma intengo...', searchBtn: 'Cinga', talkToAgent: 'Khuluma Nomsebenzi Wethu' },
    listings: { title: 'Izindawo Ezivelele', allListings: 'Bona Zonke Izindawo', forSale: 'Ithengiswa', forRent: 'Iqashiswa', viewMore: 'Bona Okunye', filters: { all: 'Konke', residential: 'Yokuhlala', commercial: 'Yohwebo', industrial: 'Yemfelandawonye', agricultural: 'Yamasimu' } },
    agents: { title: 'Abasebenzi Bethu', subtitle: 'Abochwepheshe baseHarare laseMarondera', harare: 'Ihovisi laseHarare', marondera: 'Ihovisi laseMarondera', contact: 'Xhumana Nomsebenzi' },
    about: { title: 'Mayelana loMercers', body: 'Mercers Kensington lilungu leEstate Agents Council yeZimbabwe.', council: 'Ilungu leEstate Agents Council', branches: 'Amahhovisi Amabili', branchesDetail: 'Harare & Marondera' },
    contact: { title: 'Xhumana Nathi', name: 'Igama Eligcwele', email: 'Ikheli le-imeyili', phone: 'Inombolo Yocingo', message: 'Umlayezo Wakho', send: 'Thumela Umlayezo', address: '19 Kay Gardens, Kensington, Harare, Zimbabwe' },
    chat: { title: 'Umsebenzi weMercers', subtitle: 'Buza noma yini mayelana nezindawo zethu', placeholder: 'Buza nge izindawo, amanani, izindawo...', send: 'Thumela', welcome: 'Sawubona! NginguMsebenzi weMercers. Ngingakusiza ukuthola indawo enhle eZimbabwe. Ufunani?' },
    footer: { tagline: 'Umlingani wakho wezindawo eZimbabwe', quickLinks: 'Izixhumanisi', contactUs: 'Xhumana Nathi', follow: 'Silandele', rights: '© 2026 Mercers Kensington. Amalungelo onke agciniwe.', council: 'Ilungu Elibhalisiwe leEstate Agents Council' },
  },
}
